### ISSUE TITLE
Compile Scrips

### ISSUE THREAD

**Issue by AireagoirSteam** [ps2homebrew/hdl-dump#13]
I've noticed the scripts diskload.sh and mkrel.sh nore do they compile anything using the latest ps2sdk.

[diskload.txt](https://github.com/AKuHAK/hdl-dump/files/4808595/diskload.txt)

[mkrel log.txt](https://github.com/AKuHAK/hdl-dump/files/4808599/mkrel.log.txt)

Any way to update these scripts?

**Comment by AKuHAK** [comment]
Miniopl is no longer supported, there was a plan that miniopl will be integrated into mainstream opl, but it is still the plan.

**Comment by AKuHAK** [comment]
I close this issue. In case if someone wants such a feature, please request from OPL devs.
