### ISSUE TITLE
[FR] Request - option to hide a game from HDDOSD when injecting

### ISSUE THREAD

**Issue by ghost** [ps2homebrew/hdl-dump#26]
It's possible to hide a game from the HDDOSD while having it still accessible from OPL by simply putting a + at the beginning of the partition name (https://www.ps2-home.com/forum/viewtopic.php?f=17&t=10668&p=45493#p45490)

**Comment by bignaux** [comment]
@zacchi4k : so where is the bug ? you mean add a quick option "hide" that is basicly "hdl_dump modify" prepending '+' to the name (and so eventually truncated the actual name) ?

**Comment by ghost** [comment]
Yes, I was thinking more about hdl_dumb

**Comment by bignaux** [comment]
Oki i don't work on the windows gui since i'm linux guy. Try to ask to https://github.com/israpps/HDL-Batch-installer perharps he would be interesting to provide that.

**Comment by NimrodPSI** [comment]
Actually I was rather interested in the ability to "hide" games as well. I was not sure where to ask about this but it already sorta sounds like the devs are not interested in adding this as a feature. Moreover, I have already cloned the project and made the changes necessary to replace the "PP." with a "+" instead. I am now looking for permission / good graces to fork the project and release a "NoPP" version for this exact purpose. Would that be okay with the devs here? Or would it be preferred to do a pull request and add a flag or option to inject either normally or hidden?

**Comment by ghost** [comment]
> Actually I was rather interested in the ability to "hide" games as well. I was not sure where to ask about this but it already sorta sounds like the devs are not interested in adding this as a feature. Moreover, I have already cloned the project and made the changes necessary to replace the "PP." with a "+" instead. I am now looking for permission / good graces to fork the project and release a "NoPP" version for this exact purpose. Would that be okay with the devs here? Or would it be preferred to do a pull request and add a flag or option to inject either normally or hidden?

Have you tried if it works? On my console I just add a + without removing the PP., I'm not sure if it works without it

**Comment by AKuHAK** [comment]
> Actually I was rather interested in the ability to "hide" games as well. I was not sure where to ask about this but it already sorta sounds like the devs are not interested in adding this as a feature. Moreover, I have already cloned the project and made the changes necessary to replace the "PP." with a "+" instead. I am now looking for permission / good graces to fork the project and release a "NoPP" version for this exact purpose. Would that be okay with the devs here? Or would it be preferred to do a pull request and add a flag or option to inject either normally or hidden?

such pure PR will not be accepted. For accepting new features, you should implement some sort of switch (as example `hdl_dump --hide/--unhide`) so the game settings can be changed back.
@zacchi4k just simple adding + into the beginning of the file is a bit dangerous in case you have a very long partition name, you can easily get over the limit. Replacing PP with ++ is safer.

**Comment by ghost** [comment]
.
> @zacchi4k just simple adding + into the beginning of the file is a bit dangerous in case you have a very long partition name, you can easily get over the limit. Replacing PP with ++ is safer.

The program already has to truncate the partition name when the name of the game is too long and makes it go over the 32 characters limit, so it would be sufficient to truncate one extra character

**Comment by NimrodPSI** [comment]
@AKuHAK - I understand, if I am able to implement an -h switch for the inject command would that be acceptable for a PR? I would also add a is_hidden variable to the hdl_game_type struct

@zacchi4k - Yes, I have already compiled and tried this. I was able to dump my personal game collection without any issues and they are now all hidden within HDDOSD. The partitions character limit is still taken into account with the altered code, you actually will see two extra chars in the games partition name since the PP. is replaced with a single +   All games I have tested through OPL with this install method have worked normally.

**Comment by AKuHAK** [comment]
> @AKuHAK - I understand, if I am able to implement an -h switch for the inject command would that be acceptable for a PR? I would also add a is_hidden variable to the hdl_game_type struct
> 

https://github.com/ps2homebrew/hdl-dump/blob/1a7b29b2a2c97dc29173fe7e7eb2c7d71cf50813/hdl_dump.c#L110
You can check CMD_MODIFY and just clone it with the necessary changes. This switch later will call
https://github.com/ps2homebrew/hdl-dump/blob/1a7b29b2a2c97dc29173fe7e7eb2c7d71cf50813/hdl_dump.c#L2043
`modify` function which is defined elsewhere.

As about actual switches they are defined here:
https://github.com/ps2homebrew/hdl-dump/blob/1a7b29b2a2c97dc29173fe7e7eb2c7d71cf50813/hdl_dump.c#L1862
to recognize which switch is used the first symbol will show it (yeah very bad coding practice - it is not my project ).

Don't quite understand about the `is_hidden` variable, hdl_game_type is mostly obsolete, OPL just ignores it. It can be easily lost during partition management by some third-party tools, and also you can break compatibility with some old tools that still read that header. To my mind it is pretty enough that we have + sign in the name - it is already the switch.

> The partitions character limit is still taken into account with the altered code, you actually will see two extra chars in the games partition name since the PP. is replaced with a single + All games I have tested through OPL with this install method have worked normally.

I kindly advise you to not replace `PP.` with `+`. The reason is that for PSX DVR DESR units (1st generation) we cannot use PP partition and are forced to use PC partition instead. I advise just to replace the first char (P) with a plus sign, so second character will not be lost (like `+P.HDL.GAMENAME`).

@NimrodPSI this PR will be accepted if you also implemented reversed switch (like -unhide). And of course if you not break something :D

**Comment by NimrodPSI** [comment]
@AKuHAK - I understand, but it seems that the modify command (CMD_MODIFY) currently causes HD Loader games to show as corrupted data in Browser 2.0. I have tried renaming some games using the modify command with hdl_dump rev. 47 (latest release) and with the latest development build. Both builds caused multiple test games that were injected with the inject_cd/dvd command to show up as corrupted data in HDDOSD. They could still be launched through OPL though.

A second issue I found with the existing modify command is that it breaks the game ID in the partition name. For example: Final Fantasy XII International is injected as "PP.SLPM-66750.HDL.Final Fantasy" but after using the modify command (hdl_dump modify hdd3: "Final Fantasy XII International" FFXII) it is renamed to "PP.SLUS-00000.HDL.FFXII".

I have already figured out and fixed the second issue in a test build. I do not how to fix the corrupted data issues, assuming I'm not the only one who can (re)produce them in Browser 2.0 without FMCB/FHDB. Would you like me to open an official bug report for the modify command causing corrupted data when renaming?

I can still implement a -hide switch on the inject command and -hide/-unhide switches on the modify command to rename the partitions. I can also fix the issue with the game ID being broken by the modify command while I am at it. I will initiate a PR when I'm finished and have tested it on a couple setups.  Don't worry, I will try my best to not break anything ^_^ and if I do something you don't like you can choose not to accept the commit. Here is the log when I used the modify command (this was on rev 47):

[gameidError.txt](https://github.com/ps2homebrew/hdl-dump/files/6595857/gameidError.txt)

**Comment by AKuHAK** [comment]
> @AKuHAK - I understand, but it seems that the modify command (CMD_MODIFY) currently causes HD Loader games to show as corrupted data in Browser 2.0. I have tried renaming some games using the modify command with hdl_dump rev. 47 (latest release) and with the latest development build. Both builds caused multiple test games that were injected with the inject_cd/dvd command to show up as corrupted data in HDDOSD. They could still be launched through OPL though.
> 
> A second issue I found with the existing modify command is that it breaks the game ID in the partition name. For example: Final Fantasy XII International is injected as "PP.SLPM-66750.HDL.Final Fantasy" but after using the modify command (hdl_dump modify hdd3: "Final Fantasy XII International" FFXII) it is renamed to "PP.SLUS-00000.HDL.FFXII".
> 
> I have already figured out and fixed the second issue in a test build. I do not how to fix the corrupted data issues, assuming I'm not the only one who can (re)produce them in Browser 2.0 without FMCB/FHDB. Would you like me to open an official bug report for the modify command causing corrupted data when renaming?
> 
> I can still implement a -hide switch on the inject command and -hide/-unhide switches on the modify command to rename the partitions. I can also fix the issue with the game ID being broken by the modify command while I am at it. I will initiate a PR when I'm finished and have tested it on a couple setups. Don't worry, I will try my best to not break anything ^_^ and if I do something you don't like you can choose not to accept the commit. Here is the log when I used the modify command (this was on rev 47):
> 
> [gameidError.txt](https://github.com/ps2homebrew/hdl-dump/files/6595857/gameidError.txt)

Feel free to open issues. In case you didn't finish your PR at least we will know that such a problem persists.
Yeah, I didn't check other commands when introduced `modify_header` command. Seems it breaks totally `modify` command. Nowadays I will not accept my own commits.
Corrupted data in HDD OSD means that CMD_MODIFY erased _system.cnf_ and all extended attribute data. It can be tricky to fix it.

**Comment by israpps** [comment]
i've made a temporary solution on my GUI to this issue

**Comment by AKuHAK** [comment]
Implemented in https://github.com/ps2homebrew/hdl-dump/pull/35
