### ISSUE TITLE
hdl_svr_093.elf looks for hard ipconfig.dat paths from both Memory Cards Slots 1/2, but not the HDD, ever.

### ISSUE THREAD

**Issue by ghost** [ps2homebrew/hdl-dump#27]
hdl_svr_093.elf is looking for hard set paths for the ipconfig.dat on both Memory Card slots 1/2, however, it isn't looking for the hard drive at all. I've confirmed this through trial and error and watching it default back to the default ipconfig.dat settings.

Please allow users to manually configure the path, or to add the default Free HD Boot path for ipconfig.dat, so that it can find it for those who only use the HDD version. As it is now, there's no way for HDL Dumb/Dump/HDL Svr to work right now without a memory card it seems.

**Comment by ghost** [comment]
Pull request here:
https://github.com/ps2homebrew/hdl-dump/pull/28

Cant build it cuz the server wont built on the latest SDK version, which is a bug report that hasn't been fixed since 2017.

**Comment by bignaux** [comment]
@Apocalypse612 : now since NBD server is merged in OPL, i invite you to setup a nbd client and use that instead of unmaintained hdl_svr_093.elf .

**Comment by ghost** [comment]
> 
> 
> @Apocalypse612 : now since NBD server is merged in OPL, i invite you to setup a nbd client and use that instead of unmaintained hdl_svr_093.elf .

Nice work!
