### ISSUE TITLE
[ISSUE] inject manually boot.kelf some games do not display characters

### ISSUE THREAD

**Issue by GDX-X** [ps2homebrew/hdl-dump#38]
I found a strange bug with the toc command on some partition it does not display numbers but on others it does. there are other characters like : '

suddenly when we want to inject the boot.kelf impossible to find the partition

![94bf6303285db2c021b6a2a2c490052d](https://user-images.githubusercontent.com/22562949/126912621-3ab79c19-ba20-4cdb-ab90-28bc7fb8a9d6.png)
![e401bb8c7aab6ddde0dd1547f9464cbf](https://user-images.githubusercontent.com/22562949/126912625-58af9128-cd18-45b6-b653-b1c710a647c5.png)

![b27c78fc41ce319848cb3c79a041cd29](https://user-images.githubusercontent.com/22562949/126912617-4428ad8b-1508-4f40-9b16-7b1a7b92d443.png)

**Comment by AKuHAK** [comment]
Should be fixed in https://github.com/ps2homebrew/hdl-dump/pull/39
