### ISSUE TITLE
Arguments to “inject” commands are backwards

### ISSUE THREAD

**Issue by ticky** [ps2homebrew/hdl-dump#4]
`argv[2]` is given here
https://github.com/AKuHAK/hdl-dump/blob/75df8d753757967475bf3f84d139140a933c3d91/hdl_dump.c#L2014-L2017

as “output” here
https://github.com/AKuHAK/hdl-dump/blob/75df8d753757967475bf3f84d139140a933c3d91/hdl_dump.c#L1018-L1028

but the instructions given suggest the reverse
https://github.com/AKuHAK/hdl-dump/blob/75df8d753757967475bf3f84d139140a933c3d91/hdl_dump.c#L1477-L1488

**Comment by AKuHAK** [comment]
I understand that this was an old issue :) but i dont see any "reverse":
argv[2] = output = target = PS2
argv[4] = source = input = PC
Maybe this is not the best synonyms - maybe I will change source and input, so `source` will be used in the code, but `input` in the interface, or vice versa.

**Comment by ticky** [comment]
Hmm, I think this issue may be invalid. This is an old enough thing that I can't figure out what I was talking about 😅
