### ISSUE TITLE
"Partition with such name already exists"

### ISSUE THREAD

**Issue by ayoits0913** [ps2homebrew/hdl-dump#42]
I didn't know where to ask about this

I'm trying to install several modded ISOs of RE4.. so after the first it says ""Partition with such name already exists" even though they all have different names

Can I really only do one at a time or is there a way to circumvent this?

thanks

**Comment by israpps** [comment]
That error means that a partition with such name already exists...

The key to install the same game multiple times is changing the game title... specifically on the first 14 character of game title (17 if the game was installed with latest HDL-Dump or HDL batch installer)

**Comment by ayoits0913** [comment]
> 
> 
> That error means that a partition with such name already exists...
> 
> The key to install the same game multiple times is changing the game title... specifically on the first 14 character of game title (17 if the game was installed with latest HDL-Dump or HDL batch installer)

I did. That doesn't work. Changed the iso name and title in the hdl dumb window. Still shows the error. 0.8.3

**Comment by israpps** [comment]
Try with [HDL Batch installer](https://github.com/israpps/HDL-Batch-installer)

**Comment by ayoits0913** [comment]
I use HDL server via ethernet cable to transfer games, I don't connect to the hdd directly. What does that batch installer do that renaming doesn't?

**Comment by israpps** [comment]
Try to switch to new NBD server from OPL 1.1.0

HDL SVR is outdated and abandoned

**Comment by bignaux** [comment]
Try to update your 2013 hdl_dump, you'll see we code some stuff since ...

**Comment by ayoits0913** [comment]
I think I got it working, but not with hdl dumb. 

Also sorry for the confusion I am extremely new at this if you couldn't tell lol. My friend gave me this PS2 and I just figured out how to use the server last week.

Anyways, I found this program: https://www.psx-place.com/threads/hdl_dump-gui-by-vtecorona.30023/

HDL Dump Gui. it uses HDLD svr 0.8.5 instead, and I tried installing one of the modified iso's and it worked... so between 0.8.3 and 0.8.5 something was put into place for the exact issue I'm having? 

Where can I find all of the old versions of hdld svr?? On here oldest is from last year, I'd prefer to test them all

Will test this svr with hdl dumb soon and see how it goes

The normal hdl svr 0.9.3 isn't working for me. At first it was stuck on "loading modules" straight from the usb, but then I copied it to my memory card and all I got was a black screen

**Comment by bignaux** [comment]
"The normal hdl svr 0.9.3 isn't working for me" for me neither, that's why i rewrote a new server replacement and document how to use it in the https://github.com/ps2homebrew/Open-PS2-Loader readme in nbd section. So if you want to rely on 2013 software, i won't help you. Btw it's not a bug on current software.

**Comment by ayoits0913** [comment]
> 
> 
> "The normal hdl svr 0.9.3 isn't working for me" for me neither, that's why i rewrote a new server replacement and document how to use it in the https://github.com/ps2homebrew/Open-PS2-Loader readme in nbd section. So if you want to rely on 2013 software, i won't help you. Btw it's not a bug on current software.

alright cool i'll check it out
