### ISSUE TITLE
[ISSUE]: Initialize command is broken on windows (probably other platforms too)

### ISSUE THREAD

**Issue by israpps** [ps2homebrew/hdl-dump#43]
### Checks

- [X] I have checked existing issues for duplicates and found none

### Describe the issue

After executing the initialize command the program crashed (the classic window of "program sudently stopped")

if i re-execute the command again i get this:
```console
00000008 (8): Unknown error.
```

Tests where conducted usen FreeMcBoot 1.966 MBR.KELF file and uLaunchELF KHN MBR.KELF variant

### Console model

SCPH-39001 + SCPH-10281 (anyway, this is useless, since it isn't injecting anythig)

**Comment by israpps** [comment]
Now i got a decent answer:
```console
00000008 (8): No hay suficientes recursos de memoria disponibles para procesar este comando.
```

in english:
```console
Not enough memory resources to process this command
```

**Comment by AKuHAK** [comment]
hmmm are you sure you are using initialize command in the correct way?:
https://github.com/ps2homebrew/hdl-dump#initialize
`hdl-dump.exe initialize MBR.KELF`
this is the command for injecting mbr.kelf into __.mbr partition

**Comment by israpps** [comment]
Hi, yes. I'm using it the correct way.

Initialize writes MBR instead of formatting since a long time ago.

**Comment by AKuHAK** [comment]
Bug confirmed, fix will be provided soon

**Comment by AKuHAK** [comment]
latest development build should fix this issue
