### ISSUE TITLE
Better resume capabilities

### ISSUE THREAD

**Issue by andwan0** [ps2homebrew/hdl-dump#5]
Please can you make HDL dump to work on unstable wifi connections or routers.
Sometimes my router overheats and just resets automatically. This causes HDL dumb/dump to just hang/freeze indefinitely.

**Comment by chewi** [comment]
I find it craps out even on a LAN. On the second attempt, I kept pinging in the background and found that the ping times spike up very high just before the transfer dies but then they recover and I can use hdl_dump again. It makes it practically impossible to transfer a large image though. :cry: I recall this happening some 10 years ago when I last tried so I don't think it's a new problem.

**Comment by chewi** [comment]
Ignore me, in my case, this turned out to be a faulty drive.
