### ISSUE TITLE
Cant build with newest OPL version

### ISSUE THREAD

**Issue by blackmagic0** [ps2homebrew/hdl-dump#6]
Edit: OPL has not been compatible with hdl-dump for a long time

~~OPL is now migrated to github, Ive been working on modifying the build scripts to correct this (this is not a complete solution).~~

**Comment by AKuHAK** [comment]
Miniopl has broken many many commits ago... It is not possible to make it
with just Makefile modification.

ср, 25 апр. 2018 г., 22:22 Jacob Pozaic <notifications@github.com>:

**Comment by blackmagic0** [comment]
Thanks for the quick response, Ive been slowly making the realization myself..

do you know where I can find a copy that is already compiled?
