### ISSUE TITLE
[ISSUE]: Unknown Error

### ISSUE THREAD

**Issue by kpcenti** [ps2homebrew/hdl-dump#69]
### Checks

- [X] I have checked existing issues for duplicates and found none

### Describe the issue

I'm trying to use HDL Dumb with OPL and I'm just getting Unknown Error.
I'm not really sure how to proceed with troubleshooting
![image](https://user-images.githubusercontent.com/10696951/204072705-55132fb8-e1f2-4682-9b56-69aecaf44457.png)

It seems to work fine with hdl_svr_093.elf but not with OPL. I've tried OPL v1 and v1.1.0. I'd prefer to use OPL.

### Console model

SCPH-50001

**Comment by AKuHAK** [comment]
In OPL you must use nbd server mounted as local hdd. Please check readme in opl repo on how to setup nbd server

**Comment by kpcenti** [comment]
Is this the case even in v1 OPL when it was HDL server?

**Comment by AKuHAK** [comment]
Hdl server never worked in opl.

**Comment by bignaux** [comment]
You should be able to use NBD with hdldumb on every version if you select local disk and good setup of nbd client since it works at OS level and make no difference for hdldumb.

**Comment by kpcenti** [comment]
Thanks for all the info! I appreciate it!
